### ISSUE TITLE
name 'get_device' is not defined error since update

### ISSUE THREAD

**Issue by itnassol** [gvigroux/hon#154]
Hey, been using this for months with no problems..

Here's the script that I have been using for months.

`alias: Quick Wash
sequence:
  - data:
      parameters: "{'spinSpeed':'1000'}"
      program: iot_wash_rapid_14
    action: hon.start_program
    target:
      device_id: 3a0ba196c853689da8fa2e2b2750d424
description: ""
icon: mdi:washing-machine`

After the update I get this error on running the script..

name 'get_device' is not defined

**Comment by lemuriens** [comment]
Same for me:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 362, in handle_start_program
    device      = get_device(hass, device_id)
                  ^^^^^^^^^^
NameError: name 'get_device' is not defined. Did you mean: 'get_device_id'?

**Comment by gvigroux** [comment]
Really sorry !  I forgot to test one function.
I just update it quickly. Could you please test ?

**Comment by lemuriens** [comment]
Hi, 

bug with device_id is ok but something else appended:

Enregistreur: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
intégration: Home Assistant WebSocket API (documentation, problèmes)
S'est produit pour la première fois: 16:15:44 (1 occurrences)
Dernier enregistrement: 16:15:44

[281472479212400] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 363, in handle_start_program
    command     = device.commands.get("startProgram")
                  ^^^^^^^^^^^^^^^
AttributeError: 'HonBaseCoordinator' object has no attribute 'commands'

**Comment by gvigroux** [comment]
I just update again ...  sorry

**Comment by lemuriens** [comment]
After updated to the last version, it seems to be ok.
Thank you for the job and the support for HON.
I use it daily so thank you again.

**Comment by gvigroux** [comment]
My pleasure :)

**Comment by itnassol** [comment]
All working on the washing machine here, thank you very much.
