### ISSUE TITLE
Integration cannot logi in today after HA restart.

### ISSUE THREAD

**Issue by finalbillybong** [gvigroux/hon#155]
This error in my logs:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 16:40:40 (1 occurrences)
Last logged: 16:40:40

Error setting up entry xxxxxxx@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_hon/__init__.py", line 73, in async_setup_entry
    await coordinator.device.load_commands()
  File "/config/custom_components/haier_hon/device.py", line 191, in load_commands
    self._appliance_model = commands.pop("applianceModel")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'applianceModel'
```

**Comment by rothomas** [comment]
Maybe it’s coincidence, but I also ran into a similar problem with the integration yesterday. It turned out that the hOn API site was trying to force me to change my password and returning HTML. To see if you’re hitting the same issue:

 - Visit https://account2.hon-smarthome.com/SmartHome
 - Sign in with your hOn credentials.
 - If this is your problem, you’ll be sent to a password reset page.
 - If this is not your problem, you’ll be taken to a page with a big “My Profile” button.
 - If you have to reset your password, unfortunately it seems like you’ll have to remove and re-add the integration, because it does not expose a way to reconfigure the credentials.

This worked for me, and my integration is now working again.

**Comment by slegars56** [comment]
I faced off the same problem today after having restarted HA (same message in log) .
I've been able to fix it after a manual connection to the Hon app and deactivating /reactivating the Hon integration afterwards. Weird.
Note: I did not reset my password

**Comment by Lemonadel** [comment]
> Maybe it’s coincidence, but I also ran into a similar problem with the integration yesterday. It turned out that the hOn API site was trying to force me to change my password and returning HTML. To see if you’re hitting the same issue:
> 
> * Visit https://account2.hon-smarthome.com/SmartHome
> * Sign in with your hOn credentials.
> * If this is your problem, you’ll be sent to a password reset page.
> * If this is not your problem, you’ll be taken to a page with a big “My Profile” button.
> * If you have to reset your password, unfortunately it seems like you’ll have to remove and re-add the integration, because it does not expose a way to reconfigure the credentials.
> 
> This worked for me, and my integration is now working again.

You are life saver!
I tried to set up again Hon in HA but had authentication errors in logs, however could log in mobile app without any problems.
But when I logged in this site I was prompted for password change and then could auth in HA properly and log in to mobile app as well... really really messed up on Hon side.
