### ISSUE TITLE
homeassistant.bootstrap

### ISSUE THREAD

**Issue by Anzic23** [gvigroux/hon#19]
Installed according to the instructions, air conditioners appeared in the interface. It was necessary to restart HA and now the component cannot be loaded. There is this message in the log:
```
Logger: homeassistant.bootstrap
Source: bootstrap.py:428
First occurred: 12:01:44 (3 occurrences)
Last logged: 12:03:44

Waiting on integrations to complete setup: hon
```
later a new error appeared:
```

This error occurred in custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/hon.py:92
Integration: hOn
First occurred: 12:05:46 (1 occurrences)
Last logged: 12:05:46

Error setting up entry anz@inbox.ru for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 40, in async_setup_entry
    await hon.async_authorize()
  File "/config/custom_components/hon/hon.py", line 144, in async_authorize
    if await self.async_get_frontdoor_url(self._session) == 1:
  File "/config/custom_components/hon/hon.py", line 92, in async_get_frontdoor_url
    async with self._session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError


```
Home Assistant Core 2022.6.4 in docker

**Comment by gvigroux** [comment]
It seems you cannot reach the URL: https://he-accounts.force.com/SmartHome/
Evrything is working for others.
Maybe firewall issue?
