### ISSUE TITLE
Error while setting up hon platform for sensor

### ISSUE THREAD

**Issue by Anzic23** [gvigroux/hon#30]
I have two air conditioners, they worked without problems for about a month, but the last few days one of them stopped working. The error code is the following:
Logger: homeassistant.components.sensor
Source: custom_components/hon/cooler.py:27
Integration: Сенсор (documentation, issues)
First occurred: 13:43:08 (1 occurrences)
Last logged: 13:43:08

Error while setting up hon platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hon/sensor.py", line 121, in async_setup_entry
    coordinator = HonCoolerCoordinator(hass, hon, appliance)
  File "/config/custom_components/hon/cooler.py", line 27, in __init__
    self._mac = appliance["macAddress"]
KeyError: 'macAddress'

**Comment by gvigroux** [comment]
I tried to create a new account and there is no more virtual device. In any case, I've added a check, it should not crash anymore.
