### ISSUE TITLE
install failed logs enclosed.

### ISSUE THREAD

**Issue by LeighAS** [gvigroux/hon#35]
Logger: homeassistant.components.sensor
Source: custom_components/hon/sensor.py:73
Integration: Sensor (documentation, issues)
First occurred: 00:25:49 (2 occurrences)
Last logged: 00:38:21

Error while setting up hon platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hon/sensor.py", line 73, in async_setup_entry
    if appliance["applianceTypeId"] == 1:
KeyError: 'applianceTypeId'

Logger: homeassistant.components.climate
Source: custom_components/hon/climate.py:92
Integration: Climate (documentation, issues)
First occurred: 00:25:48 (2 occurrences)
Last logged: 00:38:20

Error while setting up hon platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hon/climate.py", line 92, in async_setup_entry
    if appliance['applianceTypeId'] == 11:
KeyError: 'applianceTypeId'

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:55
Integration: hOn
First occurred: 00:25:48 (3 occurrences)
Last logged: 00:38:20

Error setting up entry a*********************h@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 55, in async_setup_entry
    if appliance['applianceTypeId'] not in [1, 2, 4, 6, 8, 9, 11]:
KeyError: 'applianceTypeId'

This error originated from a custom integration.

Logger: custom_components.hon.hon
Source: custom_components/hon/hon.py:144
Integration: hOn
First occurred: 00:38:18 (1 occurrences)
Last logged: 00:38:18

Framework update from [none] to [tr2UlkrAHzi37ijzEeD2UA]

**Comment by gvigroux** [comment]
Should be fixed. Can you please try again?
