### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by andycockers** [gvigroux/hon#38]
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/hon.py:92
Integration: hOn
First occurred: 14:56:15 (3 occurrences)
Last logged: 15:40:08

Error setting up entry xx.xx@xx.com for hon
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 40, in async_setup_entry
    await hon.async_authorize()
  File "/config/custom_components/hon/hon.py", line 144, in async_authorize
    if await self.async_get_frontdoor_url(self._session) == 1:
  File "/config/custom_components/hon/hon.py", line 92, in async_get_frontdoor_url
    async with self._session.post(
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host he-accounts.force.com:443 ssl:default [Try again]
```

(Have removed email address)

**Comment by gvigroux** [comment]
The hOn integration tries to access the URL: https://he-accounts.force.com/SmartHome/s/login/
It seems your HA installation is not able to do it.
Any firewall ?
