### ISSUE TITLE
HWD100-B14959U1UK - Unknown sensor values

### ISSUE THREAD

**Issue by roy-james** [gvigroux/hon#53]
Amazing work on this.... pretty amazed @gvigroux at how much you did last weekend. The integration picks up that I have model HWD100-B14959U1UK, firmware 5.12.0, but all three sensors show unknown. Any idea what may be causing this (message from log below)?

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hon/washdryer.py:133
Integration: hOn (documentation)
First occurred: 18:27:59 (2 occurrences)
Last logged: 18:28:29

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/config/custom_components/hon/washdryer.py", line 133, in _handle_coordinator_update
    time = int(json["delayTime"]["parNewVal"])
KeyError: 'delayTime'
`

**Comment by slegars56** [comment]
Could you please try my fork? [https://github.com/slegars56/hon](https://github.com/slegars56/hon)
If it works, I'll create a Pull Request.

**Comment by roy-james** [comment]
@slegars56, wow, perfect! 14 entities, all populated with values. Let me know if there is anything I can do to repay the favour :-)
