### ISSUE TITLE
Name Error

### ISSUE THREAD

**Issue by bvj** [gvigroux/hon#72]
```
2023-04-04 15:02:31.560 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up hon platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/hon/sensor.py", line 110, in async_setup_entry
    appliances.extend([HonBaseDryLevel(hass, coordinator, entry, appliance)])
  File "/home/homeassistant/.homeassistant/custom_components/hon/sensor.py", line 389, in __init__
    super().__init__(coordinator, appliance, "dryLevel", "Dry level")
  File "/home/homeassistant/.homeassistant/custom_components/hon/base.py", line 155, in __init__
    self.coordinator_update()
  File "/home/homeassistant/.homeassistant/custom_components/hon/sensor.py", line 400, in coordinator_update
    if drylevel in TUMBLE_DRYER_DRYL:
NameError: name 'TUMBLE_DRYER_DRYL' is not defined
```

**Comment by gvigroux** [comment]
Thanks for the issue, it will be fixed in the next release

**Comment by gvigroux** [comment]
Should Word now
