### ISSUE TITLE
Support for Flexis AC

### ISSUE THREAD

**Issue by misssfit** [gvigroux/hon#73]
Hi, do you support flexis plus ACs like AS35S2SF1FA-BH? I have added the integration but no devices are discovered (ha restarted). I have multisplit setup with 4 indoor and 1 outdoor unit.

**Comment by gvigroux** [comment]
Hi, any error in the logs ?
Are they visible in the hOn mobile app ?

**Comment by misssfit** [comment]
Unfortunately nothing in the logs. ACs added to the mobile app and working fine there

**Comment by gvigroux** [comment]
Really strange, no error when you insert your login / password? You have a success message ?

**Comment by misssfit** [comment]
Yep, I had a success message. I have removed the integration and added it again and here I have an error: 
```
Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:32
Integration: Haier hOn ([documentation](https://github.com/Andre0512/hon/), [issues](https://github.com/Andre0512/hon/issues))
First occurred: 10:55:42 PM (1 occurrences)
Last logged: 10:55:42 PM

Error setting up entry *****@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 32, in async_setup_entry
    await hon.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 54, in setup
    headers=await self._headers) as resp:
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 44, in _headers
    if await auth.authorize(self._email, self._password, self._mobile_id):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 138, in authorize
    if login_site := await self._load_login(session):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 51, in _load_login
    async with session.get(f"{const.AUTH_API}/services/oauth2/authorize/expid_Login?{params}") as resp:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by pee
```

**Comment by Krzysztonek** [comment]
Hi,
I'm not able even to add my AC (Flexis Plus: AS50S2SF1FA-CW ) to hOn app on my smartphone. My device is not recognizable by this app. I tried both serial numbers: the external unit s/n, and the internal split s/n. Both remain unknown for this app. I'm stuck... What might be wrong?

**Comment by gvigroux** [comment]
Hi, you're not using my repo but a fork of it.
Someone has made a fork and put it on HACS. My repo is not on HACS yet :(

So please take the source from here :)

**Comment by Krzysztonek** [comment]
I'm talking about the [hOn application](https://play.google.com/store/apps/details?id=com.haiereurope.hon) installed on my android phone, downloaded from Google Play. This app doesn't recognize the serial number of my Flexis Plus AC. Is it somehow connected to your repo?

**Comment by gvigroux** [comment]
Sorry @Krzysztonek I was replying to @misssfit 
For your problem I also has issues to be able to connect my device to the hOn app. Look at all possible S/N and barcode to register tour device. 
Maybe look at well as the country of your hOn account, it has to match.

**Comment by misssfit** [comment]
Thanks @gvigroux, worked as a charm! Why you don't want to add your integration to hacks?

**Comment by gvigroux** [comment]
I will work on that next week, I think I have to do lot of updates to be compatible

**Comment by Doktor-X** [comment]
HoN integration on HACS is not working with AC's at least my flexis, so ill use this integration from gvigroux for now
