### ISSUE TITLE
Error setting up entry ubbwp.pl for hon

### ISSUE THREAD

**Issue by Lisu25** [gvigroux/hon#77]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 70, in async_setup_entry
    coordinator = await hon.async_get_coordinator(appliance)
  File "/config/custom_components/hon/hon.py", line 89, in async_get_coordinator
    coordinator = HonBaseCoordinator( self._hass, self, appliance)
  File "/config/custom_components/hon/base.py", line 31, in __init__
    self._mac       = appliance["macAddress"]
KeyError: 'macAddress'
```

Air condition model: as35tamhra-c

**Comment by gvigroux** [comment]
I will fix it in 30 min
